Improve exception structure and handling
withlogicco/billit-python-sdk pull request #27
Opened 2022-08-19 10:20 UTC by phemmylintry

closes #25

2022-08-19 11:37 UTC, parisk commented on billit/client.py
> +            return response
It looks like this will break existing implementations, so I suggest bringing it back to how it was.

2022-08-19 11:37 UTC, parisk commented on billit/client.py
>                  error = f"Message: {resp['message']}, Error details: {resp.get('errors', None)}, {resp.get('data', None)}"
We need to take into account that `message` won't always be available, as described in the last todo in https://github.com/withlogicco/billit-python-sdk/issues/25.

2022-08-19 11:37 UTC, parisk requested changes
Great job! A few changes 😄.

2022-08-22 07:12 UTC, akalipetis approved these changes
LGTM

Just one suggestion, feel free to change the code or leave it as is.

2022-08-22 07:12 UTC, akalipetis commented on billit/client.py
> +                    error = f"Message: {resp.get('msg')} , Error details: {resp.get('errors')}, {resp.get('data')}"
We could use early raises here, to make code reading a bit easier.

```suggestion
                if "message" in resp:
                    error = f"Message: {resp.get('message')} , Error details: {resp.get('errors')}, {resp.get('data')}"
                    raise APIError(error, response)

                if "msg" in resp:
                    error = f"Message: {resp.get('msg')} , Error details: {resp.get('errors')}, {resp.get('data')}"
                    raise APIError(error, response)
```

2022-08-22 15:01 UTC, parisk approved these changes
LGTM 🚀

2022-08-22 15:02 UTC, merged