Ocp client methods
withlogicco/billit-python-sdk pull request #38
Opened 2022-09-05 02:47 UTC by phemmylintry

closes #30

2022-09-05 02:48 UTC, phemmylintry commented
@parisk @akalipetis Please review

2022-09-07 16:55 UTC, parisk requested changes
Great job @phemmylintry! Just one update and we are good to go 😄.

2022-09-07 16:55 UTC, parisk commented on billit/client.py
> +class Ocp(SubClient):
Let's rename this to OCP, since it's an abbreviation.

2022-09-07 16:55 UTC, parisk commented on billit/client.py
> +        self.ocp = Ocp(self)
Update according to https://github.com/withlogicco/billit-python-sdk/pull/38/files#diff-f5cff635bc137e72aa003a9abb9891dfabc0c0a1fcaeaf400b38f8c6ce36215eR455

2022-09-08 07:17 UTC, parisk approved these changes
LGTM 🚀

2022-09-08 07:17 UTC, merged