bill-it payment sdk
withlogicco/billit-python-sdk pull request #45
Opened 2022-09-14 13:15 UTC by phemmylintry

closes #31

2022-09-14 13:20 UTC, phemmylintry commented
@akalipetis @parisk Please review. Thanks

2022-09-14 13:24 UTC, parisk requested changes
Great job @phemmylintry! Just a comment.

2022-09-14 13:24 UTC, parisk commented on billit/client.py
> +        invoices_paid: List,
@phemmylintry let's create an `InvoicePaid` type according to the payload described in https://developer.billit.io/docs/billitdocs/e8bc28eaa24ea-create-a-new-payment and mark `invoices_paid` as a list of `InvoicePaid` (it should be `InvoicePaid[]`).

2022-09-15 12:22 UTC, phemmylintry commented on billit/client.py
> +        invoices_paid: List,
@parisk I'm not sure I get it. The type is a list, right?

2022-09-15 12:44 UTC, parisk commented on billit/client.py
> +        invoices_paid: List,
Yes. `List` is quite generic. We want to indicate that it is a list of `PaidInvoice`. So we need to:

- [ ] Declare a new `PaidInvoice` type, similarly to `Tax`[^1]
- [ ] Indicate that `invoices_paid` is a list of `PaidInvoice` (this should be enough `: PaidInvoice[]`)

Let me know if you would like further clarifications

[^1]: https://github.com/withlogicco/billit-python-sdk/blob/a5e028185f80d73accbeab55ad35d8d0fc27b160/billit/utils/tax_utils.py#L4-L7

2022-09-16 06:13 UTC, parisk approved these changes
LGTM 🍰

2022-09-16 06:13 UTC, merged