feat: Account api endpoint
withlogicco/billit-python-sdk pull request #6
Opened 2022-05-25 08:15 UTC by phemmylintry

2022-05-25 09:41 UTC, phemmylintry commented
@parisk I can't add you as reviewer

2022-05-25 09:56 UTC, parisk commented
No worries, did it myself.

2022-05-25 11:11 UTC, parisk requested changes
Great job here 😄. I have quite a few comments, as I am a stickler with a few things, but we're on a good direction.

After we ensure the functionality we will move on to improve code base even better 🥳.

2022-05-25 11:11 UTC, parisk commented on billit/billit.py
> +from dotenv import load_dotenv
Let's remove `dotenv`. We do not need the library to be aware of `.env` files.

2022-05-25 11:11 UTC, parisk commented on billit/billit.py
> +load_dotenv()
ditto: https://github.com/withlogicco/billit-python-sdk/pull/6/files#diff-a23724681a84b4e549ef415e04811a1bdad0afc0419c78915677d6d434a356dcR4

2022-05-25 11:11 UTC, parisk commented on billit/billit.py
> +        self.base_url = SANDBOX_BASE_URL
Let's

- [ ] Add a base URL parameter, defaulting to `SANDBOX_BASE_URL`
- [ ] Not use environment variables in here and just keep them for our personal testing files.

```suggestion
    def __init__(self, api_key, base_url=SANDBOX_BASE_URL):
        self.api_key = api_key
        self.base_url = base_url
```

2022-05-25 11:11 UTC, parisk commented on billit/billit.py
> +            "Authorization": "Bearer {}".format(self.api_key),
A couple of comments here:

 - [ ] I think we do not need the empty `Accept` header.
 - [ ] Let's opt-in for a custom Authentication mechanism[^1]
 - [ ] Let's use f-strings[^2], instead of format

[^1]: https://requests.readthedocs.io/en/latest/user/advanced/#custom-authentication
[^2]: https://peps.python.org/pep-0498/

2022-05-25 11:11 UTC, parisk commented on billit/billit.py
> +    # TODO: Implement this
let's remove this.

2022-05-25 11:11 UTC, parisk commented on requirements.txt
> +python-dotenv==0.20.0
We should use Poetry[^1], instead of `requirements.txt`, as it enables easier publication of libraries.

[^1]: https://python-poetry.org/

2022-05-25 11:28 UTC, phemmylintry commented on .gitignore
> +.vscode/
I'm sure I understand this comment

2022-05-25 11:35 UTC, parisk commented on .gitignore
> +.vscode/
Let's add an EOL (End of Line)[^1] at the end of file[^2].

[^1]: https://en.wikipedia.org/wiki/Newline
[^2]: https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

2022-05-25 11:51 UTC, phemmylintry commented on .gitignore
> +.vscode/
got it

2022-05-25 15:22 UTC, akalipetis commented on billit/billit.py
> +        url = SANDBOX_BASE_URL + endpoint
```suggestion
        url = this.base_url + endpoint
```

We should use the provided base URL here.

2022-05-25 15:22 UTC, akalipetis commented on billit/billit.py
> +        return response.json()
We should check that the request was successful here, catching 4XX and 5XX errors.

2022-05-26 11:35 UTC, parisk requested changes
A few more changes. We are on a great track here 😄.

2022-05-26 11:35 UTC, parisk commented on billit/billit.py
> +    class ApiError(Exception):
Shouldn't this inherit from `billit.errors.Error`?

2022-05-26 11:35 UTC, parisk commented on billit/billit.py
> +    class AuthenticationError(Exception):
Shouldn't this inherit from `billit.errors.Error`?

2022-05-26 11:35 UTC, parisk commented on billit/billit.py
> +            Exception.__init__(self, error_message)
```suggestion
            super().__init__(error_message)
```

2022-05-26 11:35 UTC, parisk commented on billit/billit.py
> +            return Client.ApiError(error, response.status_code)
Why not just

```suggestion
            raise Client.ApiError(error, response.status_code)
```

2022-05-26 11:39 UTC, parisk commented on billit/billit.py
> +from constants import (
```suggestion
from .auth import BillitAuthentication
from .constants import (
```

2022-05-26 11:45 UTC, parisk requested changes
Two more comments I forgot to mention before:

- [ ] We should use relative imports
- [ ] We should rename `billit/billit.py` to `billit/client.py`

2022-05-26 12:47 UTC, parisk requested changes
Two last comments and we are good to go 🥳

2022-05-26 12:47 UTC, parisk commented on billit/client.py
> +                error = f"{response.text}"
No need for `if/else`. Let's just default:

```suggestion
            error = f"{response.text}"
            if "application/json" in response.headers["Content-Type"]:
                error = f"{response.json()['message']}"
```

2022-05-26 12:47 UTC, parisk commented on billit/client.py
> +            raise Exception(f"Invalid environment provided: {environment}")
Let's create an `InvalidEnvironment` subclass of Exception for this.

2022-05-26 12:57 UTC, parisk approved these changes
Great job @phemmylintry! LGTM 🚀

2022-05-26 12:58 UTC, merged