feat: Invoice sub client and methods
withlogicco/billit-python-sdk pull request #7
Opened 2022-05-31 09:23 UTC by phemmylintry

2022-05-31 09:26 UTC, phemmylintry commented
#5 
#4

2022-05-31 13:01 UTC, parisk requested changes
Good job @phemmylintry 👍. Let's fix a few things and I think we can move on.

2022-06-01 07:58 UTC, phemmylintry commented on billit/utils/tax_utils.py
> +        return asdict(self)
@parisk where will the asdcit() function be used then?

2022-06-01 08:15 UTC, parisk commented on billit/utils/tax_utils.py
> +        return asdict(self)
We should use it before passing data to `_handle_request`. Example:

```py
def create(self, customerId: int, sendMail: bool, ..., taxes: Tax, ...):
    data = {
        "customerId": customerId,
        "sendMail": sendMail,
        ...,
        "taxes": dataclasses.as_dict(taxes),
        ...,
    }
    return self.client._handle_request("POST", "/invoices", data=data)
```

2022-06-01 14:19 UTC, parisk requested changes
Great job @phemmylintry. We are almost there.  Let's make arguments PEP8 compliant and then we can merge this.

2022-06-01 14:19 UTC, parisk commented on billit/client.py
> +        }
There is one last thing we need to take care here. We need to have Python arguments in snake case[^1], as this is the official coding style proposed by PEP8[^2] (e.g. use `customer_id` in Python, as described in #4, and convert it to `customerId` before sending to the API).

In order to make this easier and DRY between `create` and `update`, I suggest doing something like the following:

```py
class Invoices(SubClient):
    _args_api_mappings = {
        "customer_id": "customerId",
        "send_mail": "sendMail",
        # ...
    }
    
    def create(self, customer_id: int, send_mail: bool, ...):
        data = {
            self._args_api_mappings["customer_id"]: customer_id,
            self._args_api_mappings["send_mail"]: send_mail,
            # ...
        }
        return self.client._handle_request("POST", "/invoices", data=data)
    
    # ...
    
    def update(self, customer_id: int, send_mail: bool, ...):
        data = {
            self._args_api_mappings["customer_id"]: customer_id,
            self._args_api_mappings["send_mail"]: send_mail,
            # ...
        }
        return self.client._handle_request("PUT", "/invoices", data=data)
```

[^1]: https://en.wikipedia.org/wiki/Snake_case
[^2]: https://peps.python.org/pep-0008/#function-and-variable-names

2022-06-02 09:18 UTC, parisk commented on billit/client.py
> +        isPaid: bool,
```suggestion
        is_paid: bool,
```

2022-06-02 09:19 UTC, parisk approved these changes
Great job! 👏 👏 👏 

LGTM ✌️

2022-06-02 10:19 UTC, merged